### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Wangze6** [tyotakuki/ManchuOCR#6]
Traceback (most recent call last):
  File "/mnt/c/Users/25062/Desktop/ManchuOCR-main/readmanchu.py", line 230, in <module>
    main()
  File "/mnt/c/Users/25062/Desktop/ManchuOCR-main/readmanchu.py", line 118, in main
    image_shape = (image_color.shape[0], image_color.shape[1])
AttributeError: 'NoneType' object has no attribute 'shape'

这个怎么回事有人知道吗？

**Comment by Comet0322** [comment]
It's probably because the image did not load correctly, could you please check the path?
